import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/theme-provider'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import './globals.css'
import { Toaster } from "@/components/ui/sonner";
import Nav from '@/components/Nav'
import { GeistSans } from 'geist/font/sans'

export const metadata: Metadata = {
  title: 'Zephyr',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={GeistSans.className}>
          <ThemeProvider attribute='class' defaultTheme='dark'>
          <Toaster />
          <Nav />
          {children}
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
